Repository dask-contrib/dask-sql, pull requests merged in 2022-06, with the labels that each got.

#542 [REVIEW] Add support for `UNION`
  dask_planner/src/sql/logical.rs
  dask_planner/src/sql/logical/union.rs
  dask_sql/physical/rel/logical/union.py
  tests/integration/test_compatibility.py
  tests/integration/test_union.py
Labels: datafusion

#559 [REVIEW] Fix issue with duplicates in column renaming
  dask_sql/datacontainer.py
  dask_sql/physical/rel/base.py
  tests/integration/test_union.py
Labels: bug

#572 [DF] Add `@ayushdg` and `@galipremsagar` to rust codeowners
  .github/CODEOWNERS
Labels: meta, datafusion

#576 Datafusion upstream merge
  .github/cluster-upstream.yml
  .github/cluster.yml
  .github/workflows/datafusion-sync.yml
  .github/workflows/test-upstream.yml
  .github/workflows/test.yml
  continuous_integration/environment-3.10-dev.yaml
  continuous_integration/environment-3.8-dev.yaml
  continuous_integration/environment-3.9-dev.yaml
  continuous_integration/gpuci/axis.yaml
  continuous_integration/recipe/meta.yaml
  dask_planner/src/expression.rs
  dask_planner/src/sql/types.rs
  dask_sql/context.py
  dask_sql/datacontainer.py
  dask_sql/input_utils/dask.py
  dask_sql/input_utils/location.py
  dask_sql/input_utils/pandaslike.py
  dask_sql/integrations/fugue.py
  dask_sql/physical/rel/logical/aggregate.py
  dask_sql/physical/rel/logical/filter.py
  dask_sql/physical/rex/convert.py
  dask_sql/physical/rex/core/__init__.py
  dask_sql/physical/rex/core/literal.py
  dask_sql/physical/rex/core/subquery.py
  dask_sql/physical/utils/map.py
  dask_sql/physical/utils/sort.py
  docker/conda.txt
  docker/main.dockerfile
  docs/environment.yml
  docs/requirements-docs.txt
  docs/source/api.rst
  docs/source/fugue.rst
  docs/source/index.rst
  setup.py
  tests/integration/test_analyze.py
  tests/integration/test_compatibility.py
  tests/integration/test_create.py
  tests/integration/test_filter.py
  tests/integration/test_groupby.py
  tests/integration/test_jdbc.py
  tests/integration/test_join.py
  tests/integration/test_select.py
Labels: datafusion

#585 Datafusion year & support for DaskSqlDialect
  dask_planner/Cargo.toml
  dask_planner/src/dialect.rs
  dask_planner/src/expression.rs
  dask_planner/src/lib.rs
  dask_planner/src/sql.rs
  dask_sql/physical/rex/core/call.py
  tests/integration/test_rex.py
Labels: datafusion

#588 Optimization rule to optimize out nulls for inner joins
  dask_planner/Cargo.toml
  dask_planner/src/sql/logical.rs
  dask_planner/src/sql/logical/limit.rs
  dask_planner/src/sql/logical/offset.rs
  dask_planner/src/sql/optimizer.rs
  dask_sql/context.py
  dask_sql/physical/rel/logical/__init__.py
  dask_sql/physical/rel/logical/limit.py
  dask_sql/physical/rel/logical/offset.py
Labels: datafusion

#599 Datafusion IndexError - Return fields from the lhs and rhs of a join
  dask_planner/src/sql/logical.rs
  dask_sql/physical/rel/logical/join.py
  tests/integration/test_join.py
Labels: bug, datafusion

#602 Search all schemas when attempting to locate index by field name
  dask_planner/src/expression.rs
Labels: datafusion
