Repository dask-contrib/dask-sql, pull requests merged in 2022-08, with the labels that each got.

#545 Port window logic to datafusion
  dask_planner/src/expression.rs
  dask_planner/src/sql/logical.rs
  dask_planner/src/sql/logical/sort.rs
  dask_planner/src/sql/logical/window.rs
  dask_sql/physical/rel/logical/sort.py
  dask_sql/physical/rel/logical/window.py
  tests/integration/test_compatibility.py
  tests/integration/test_over.py
Labels: datafusion

#653 Invalid crossjoin in plan
  continuous_integration/environment-3.10-dev.yaml
  continuous_integration/environment-3.8-dev.yaml
  continuous_integration/environment-3.9-dev.yaml
  continuous_integration/recipe/meta.yaml
  dask_planner/Cargo.toml
  dask_planner/src/sql.rs
  tests/integration/test_compatibility.py
Labels: bug, datafusion

#638 Datafusion expand scalarvalue catchall
  dask_planner/src/expression.rs
  dask_sql/mappings.py
  dask_sql/physical/rex/core/literal.py
  tests/integration/test_rex.py
Labels: datafusion

#671 Remove un-necessary sqlparser dependency and duplicate Dialect defini…
  dask_planner/Cargo.toml
  dask_planner/src/dialect.rs
  dask_planner/src/sql.rs
Labels: datafusion

#629 Add STDDEV, STDDEV_SAMP, and STDDEV_POP
  dask_sql/physical/rel/logical/aggregate.py
  tests/integration/test_groupby.py
Labels: datafusion

#713 Introduce 'schema' to the DaskTable instance and modify context.fqn t…
  dask_planner/src/sql/table.rs
  dask_sql/context.py
  dask_sql/physical/rel/logical/table_scan.py
Labels: datafusion

#715 Support for DISTRIBUTE BY
  dask_planner/Cargo.toml
  dask_planner/src/sql.rs
  dask_planner/src/sql/logical.rs
  dask_planner/src/sql/logical/repartition_by.rs
  dask_sql/context.py
  dask_sql/physical/rel/custom/distributeby.py
  dask_sql/physical/rel/logical/table_scan.py
  tests/integration/test_distributeby.py
Labels: datafusion

#714 Datafusion create table with
  dask_planner/src/parser.rs
  dask_planner/src/sql.rs
  dask_planner/src/sql/logical.rs
  dask_planner/src/sql/logical/create_table.rs
  dask_planner/src/sql/parser_utils.rs
  dask_planner/src/sql/table.rs
  dask_sql/physical/rel/custom/create_table.py
  dask_sql/utils.py
  tests/integration/test_create.py
  tests/integration/test_intake.py
Labels: datafusion

#675 Stop overwriting aggregations on same column
  dask_sql/physical/rel/logical/aggregate.py
  tests/integration/test_groupby.py
Labels: datafusion

#727 {CREATE | USE | DROP} Schema support
  .gitignore
  dask_planner/src/parser.rs
  dask_planner/src/sql.rs
  dask_planner/src/sql/logical.rs
  dask_planner/src/sql/logical/create_catalog_schema.rs
  dask_planner/src/sql/logical/create_view.rs
  dask_planner/src/sql/logical/drop_schema.rs
  dask_planner/src/sql/logical/use_schema.rs
  dask_planner/src/sql/table.rs
  dask_sql/physical/rel/custom/create_schema.py
  dask_sql/physical/rel/custom/create_table_as.py
  dask_sql/physical/rel/custom/drop_schema.py
  dask_sql/physical/rel/custom/switch_schema.py
  dask_sql/physical/rel/logical/project.py
  tests/integration/test_schema.py
Labels: enhancement, datafusion
